package util

import (
	"bytes"
	"fmt"
	"html/template"
	"os"

	"github.com/resend/resend-go/v3"
	"github.com/shravanasati/scopex-go-assignment/model"
)

const emailTemplateHTML = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 20px auto; padding: 20px; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
        .header { text-align: center; padding-bottom: 20px; border-bottom: 2px solid #eee; margin-bottom: 20px; }
        .header h2 { color: #2c3e50; margin: 0; }
        .content { padding: 0 10px; }
        .info-group { margin-bottom: 15px; }
        .label { font-weight: 600; color: #555; display: inline-block; width: 120px; }
        .value { color: #333; }
        .stats { display: flex; justify-content: space-around; margin-top: 30px; background-color: #f9f9f9; padding: 15px; border-radius: 6px; }
        .stat-box { text-align: center; }
        .stat-number { display: block; font-size: 24px; font-weight: bold; }
        .stat-number.present { color: #27ae60; }
        .stat-number.absent { color: #c0392b; }
        .stat-label { font-size: 14px; color: #777; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Attendance Report</h2>
        </div>
        <div class="content">
            <div class="info-group">
                <span class="label">Student Name:</span>
                <span class="value">{{.StudentName}}</span>
            </div>
            <div class="info-group">
                <span class="label">Student ID:</span>
                <span class="value">{{.StudentID}}</span>
            </div>
            <div class="info-group">
                <span class="label">Email:</span>
                <span class="value">{{.StudentEmail}}</span>
            </div>
            
            <div class="stats">
                <div class="stat-box">
                    <span class="stat-number present">{{.PresentCount}}</span>
                    <span class="stat-label">Days Present</span>
                </div>
                <div class="stat-box">
                    <span class="stat-number absent">{{.AbsentCount}}</span>
                    <span class="stat-label">Days Absent</span>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>Generated by ScopeX Attendance System</p>
        </div>
    </div>
</body>
</html>
`

func SendEmail(report model.AttendanceReport) {
	apiKey := os.Getenv("RESEND_API_KEY")
	if apiKey == "" {
		fmt.Println("skipping email notification due to absence of env RESEND_API_KEY")
		return
	}

	tmpl, err := template.New("email").Parse(emailTemplateHTML)
	if err != nil {
		fmt.Printf("failed to parse email template: %v\n", err)
		return
	}

	var body bytes.Buffer
	if err := tmpl.Execute(&body, report); err != nil {
		fmt.Printf("failed to execute email template: %v\n", err)
		return
	}

	subject := fmt.Sprintf("Attendance Report for %s", report.StudentName)

	client := resend.NewClient(apiKey)

	params := &resend.SendEmailRequest{
		From:    "Acme <onboarding@resend.dev>",
		To:      []string{"delivered@resend.dev"},
		Html:    body.String(),
		Subject: subject,
	}

	sent, err := client.Emails.Send(params)
	if err != nil {
		fmt.Println("error in email sending:", err.Error())
		return
	}
	fmt.Println("email notification sent to", report.StudentEmail, "id:", sent.Id)
}
